trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  artifactName: 'drop'

stages:
  - stage: Build
    displayName: 'Build and Test Stage'
    jobs:
      - job: MavenBuild
        displayName: 'Build with Maven'
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'Amazon/pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              mavenVersionOption: 'Default'
              options: '-Xmx1024m'

          - task: CopyFiles@2
            inputs:
              contents: '**/target/*.jar'
              targetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: '$(artifactName)'
              publishLocation: 'Container'

  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeployApp
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: $(artifactName)

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'vivek_sc'
                    appType: 'webApp'
                    appName: 'Amazon'
                    package: '$(Pipeline.Workspace)/$(artifactName)/*.jar'
